%%{init: {
  "flowchart": {
    "curve": "stepBefore",
    "htmlLabels": true,
    "defaultRenderer": "elk",
    "stroke": {
      "color": "#222222",
      "width": 2
    }
  }
}%%
flowchart TB

  subgraph Customer["Customer / Channels"]
  direction LR
    subgraph CustomerPortal["Customer Portal"]
      CustomUI["Custom UI"]
    end
    subgraph StellarusPortal["Stellarus Portal"]
      StellarusUI["Stellarus UI"]
    end

    StellarusSDK["Stellarus SDK"]

    CustomUI---StellarusSDK
    StellarusUI---StellarusSDK
  end

  subgraph StellarusPlatform["Stellarus Platform"]
    direction TB
    CCS["Auth / Customer Config Service"]

    subgraph IntBroker["Chat Broker"]
      DataEnrich["Data Enrichment"]
      Conversation["Conversation Management"]


      DataEnrich --- Conversation
    end

    subgraph StellarusAI["Stellarus AI"]
    direction TB
      SierraAI["Sierra.ai"]
      MemberAgent["Member Agent"]
      CSRAgent["CSR Agent"]
    end
    
    subgraph DataServices["Data Services"]
      direction TB
      BenefisService["Benefis Service"]
      DataX["DataX Service"]
      DataY["DataY Service"]
    end
    %% StellarusAI---DataServices

    CCS===IntBroker
    IntBroker===StellarusAI
    IntBroker===DataServices
    
  end
  CustomerCCaS["Customer CCaS<br/>(eg. Genesys)"]

  StellarusSDK===StellarusPlatform
  StellarusPlatform===|Escalations| CustomerCCaS

  classDef notMVP fill:#676868,stroke:#d4d5d5,stroke-width:2px;
  class DataX,DataY,MemberAgent notMVP;