gantt
    title Mem-Chat Platform Delivery Timeline
    dateFormat  YYYY-MM-DD
    axisFormat  %b %d

    section SDK Foundation
    Complete MVP Mem-Chat Direct Genesis/Sierra.ai SDKs :memchat_MVP, 2026-06-04, 2026-07-01
    Stellarus-MemChat SDK (With Genesis/Sierra.ai) :Stellarus_SDK_MVP, 2026-06-04, 2026-07-15

    section Helm Platform <dark prod>
    Helm <compass> Platform (With Genesis/Sierra.ai) :platform_MVP, 2026-06-04, 2026-08-15
    Help <compass> Platform Telemetry Dashboard :platform_MVP, 2026-07-01, 2026-08-01

    section Help Platform <live>
    Connect Stellarus Mem-Chat-SDK to Helm <compass> Platform :platform_MVP_Live, 2026-08-15, 2026-09-01
    
